spring.application.name=microservice
server.port=8082
resilience4j.circuitbreaker.instances.suggestions.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.suggestions.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.suggestions.wait-duration-in-open-state=60s
resilience4j.circuitbreaker.instances.suggestions.permitted-number-of-calls-in-half-open-state=2